version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: facilita_juridico_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
