openapi: 3.0.0
info:
  title: API de Gerenciamento de Clientes
  description: Esta API é utilizada para gerenciar clientes de uma empresa de limpeza residencial.
  version: '1.0.0'
servers:
  - url: http://localhost:3000/
paths:
  /clientes:
    get:
      summary: Lista todos os clientes
      responses:
        '200':
          description: Uma lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Cadastra um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente criado com sucesso
  /rota:
    get:
      summary: Lista os clientes ordenados pela proximidade com a empresa
      responses:
        '200':
          description: Uma lista de clientes ordenados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'

components:
  schemas:
    Cliente:
      type: object
      required:
        - nome
        - email
        - telefone
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        coordenada_x:
          type: integer
        coordenada_y:
          type: integer
